### ISSUE TITLE
This needs to be checked

### ISSUE THREAD

**Issue by niraj97** [shirosaidev/stocksight#13]
Got some error on this line of the code in Sentiment.py line 788 
stream.filter(follow=useridlist, languages=['en'])

**Comment by shirosaidev** [comment]
what's the error? What version of Python? Try with Python 3.6.x

**Comment by niraj97** [comment]
I have the latest Python 2.7 and 3.6 installed.
got an error stating required string got int.
as much as i can understand userlist is all integer variables but the stream.filter follow requires string input.

**Comment by pcamelo** [comment]
Just change line 462 from `sentiment.py` to `u = line.strip()`.

**Comment by shirosaidev** [comment]
this has been patched in v0.1-b.6
