### ISSUE TITLE
Lacking documentation to get up and running

### ISSUE THREAD

**Issue by egeste** [shirosaidev/stocksight#21]
After cloning this repo and running the appropriate docker-compose commands to get the service(s) running, I had a very difficult time figuring out how to access the Kibana user interface. The port is not documented in the README, and I ended up discovering it in the docker-compose file. After I was able to access the Kibana user interface, I'm prompted with a request for an "index pattern". I have no clue what this is, or what it needs to be, and I don't see any reference to it in the README.

**Comment by shirosaidev** [comment]
I added some more info in the readme for kibana, if you get stuck jump on the slack workspace.
