### ISSUE TITLE
Kibana Integration

### ISSUE THREAD

**Issue by jcherrera** [shirosaidev/stocksight#5]
I am having trouble regarding:
"Load 'stocksight' index in Kibana and import export.json file for visuals/dashboard."

I already started Kibana and Elasticsearch in docker images and I am successfully running sentiment.py with keywords. I can load the stocksight index in kibana but where do I import the export.json file. Could you please elaborate on how to do so?

**Comment by DanielHHowell** [comment]
@jcherrera what was the solution? Feel the documentation is pretty sparse here
