### ISSUE TITLE
Getting Started with Stock Sight

### ISSUE THREAD

**Issue by zacharimayer** [shirosaidev/stocksight#9]
First of all I would like to say this is a great idea and I cannot wait to be up and running with this :) I have been trying to get setup but I seem to be running into a few issues -- 

1. When running sentiment.py I am getting this, I would like to point out as I am used to working with Python I am no expert & I apologize in advance if I sound like a noob XD

`
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/Users/zachmayer/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/share/nltk_data'
    - '/Library/Frameworks/Python.framework/Versions/3.7/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
` 

2. What would be the steps in order to get the GUI dashboard up and running as well with Kibana? I would like to work on a detailed guide for other users that are not too familiar with it so more people can benefit from this project!

Thanks!!!

**Comment by shirosaidev** [comment]
1) You need to run the Python 3 interpreter and run
```
import nltk
nltk.download('punkt')
```

2) Import the json file into Kibana 5.x
